---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
spec:
  routes:
   - kind: Rule
     match: Host(`34.94.61.235`)
     services:
        - kind: Service
          name: whoamiv1
          port: 80
